[[constraint]]
  branch = "master"
  name = "code.gitea.io/sdk"

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.2.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[prune]
  go-tests = true
  unused-packages = true
